from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
import time
from dataclasses import dataclass
from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parent
VENV_DIR = ROOT_DIR / ".venv"
REQUIREMENTS_PATH = ROOT_DIR / "requirements.txt"
BOOTSTRAPPED_ENV = "ANOMALY_PIPELINE_BOOTSTRAPPED"


def venv_python_path() -> Path:
    if os.name == "nt":
        return VENV_DIR / "Scripts" / "python.exe"
    return VENV_DIR / "bin" / "python"


def venv_pip_command() -> list[str]:
    return [str(venv_python_path()), "-m", "pip"]


def run_bootstrap_command(command: list[str], *, cwd: Path = ROOT_DIR) -> None:
    print(f"$ {' '.join(command)}", flush=True)
    subprocess.run(command, cwd=cwd, check=True)


def create_venv_if_missing() -> None:
    python_path = venv_python_path()
    if python_path.exists():
        print(f"[bootstrap] Existing virtual environment found: {VENV_DIR}", flush=True)
        return

    print(f"[bootstrap] Creating virtual environment: {VENV_DIR}", flush=True)
    run_bootstrap_command([sys.executable, "-m", "venv", str(VENV_DIR)])


def parse_requirement_names(path: Path) -> list[str]:
    if not path.exists():
        raise FileNotFoundError(f"requirements.txt not found: {path}")

    package_names: list[str] = []
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or line.startswith("-"):
            continue

        line = line.split(";", 1)[0].strip()
        package_name = re.split(r"[<>=!~\[]", line, maxsplit=1)[0].strip()
        if package_name:
            package_names.append(package_name)

    return package_names


def missing_requirements(requirement_names: list[str]) -> list[str]:
    missing: list[str] = []
    for package_name in requirement_names:
        result = subprocess.run(
            [*venv_pip_command(), "show", package_name],
            cwd=ROOT_DIR,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=False,
        )
        if result.returncode != 0:
            missing.append(package_name)

    return missing


def install_requirements_if_needed() -> None:
    requirement_names = parse_requirement_names(REQUIREMENTS_PATH)
    missing = missing_requirements(requirement_names)
    if not missing:
        print("[bootstrap] Requirements already installed. Skipping pip install.", flush=True)
        return

    print(f"[bootstrap] Missing packages: {', '.join(missing)}", flush=True)
    run_bootstrap_command([*venv_pip_command(), "install", "-r", str(REQUIREMENTS_PATH)])


def running_inside_project_venv() -> bool:
    current = Path(sys.executable).resolve()
    expected = venv_python_path().resolve()
    return current == expected


def reexec_inside_venv_if_needed() -> None:
    if running_inside_project_venv():
        return

    env = os.environ.copy()
    env[BOOTSTRAPPED_ENV] = "1"
    command = [str(venv_python_path()), str(Path(__file__).resolve()), *sys.argv[1:]]
    print("[bootstrap] Restarting pipeline with project virtual environment.", flush=True)
    result = subprocess.run(command, cwd=ROOT_DIR, env=env, check=False)
    raise SystemExit(result.returncode)


def bootstrap_environment() -> None:
    if os.environ.get(BOOTSTRAPPED_ENV) == "1" and running_inside_project_venv():
        return

    create_venv_if_missing()
    install_requirements_if_needed()
    reexec_inside_venv_if_needed()


if "--skip-setup" not in sys.argv:
    bootstrap_environment()

from rich.console import Console
from rich.panel import Panel
from rich.progress import Progress, SpinnerColumn, TextColumn, TimeElapsedColumn
from rich.table import Table


console = Console()


@dataclass(frozen=True)
class PipelineStep:
    name: str
    command: list[str]
    outputs: tuple[Path, ...] = ()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run the full synthetic fraud anomaly detection pipeline."
    )
    parser.add_argument(
        "--skip-setup",
        action="store_true",
        help="Skip venv/dependency checks. Mainly useful when already inside .venv.",
    )
    parser.add_argument(
        "--rows",
        type=int,
        default=100_000,
        help="Rows generated by DataSet/generate_synthetic_fraud_dataset.py.",
    )
    parser.add_argument(
        "--fraud-rate",
        type=float,
        default=0.05,
        help="Fraud rate used by the synthetic dataset generator.",
    )
    parser.add_argument(
        "--random-state",
        type=int,
        default=42,
        help="Random state passed to synthetic generation and model training.",
    )
    parser.add_argument(
        "--sample-size",
        type=int,
        default=100_000,
        help="Pipeline sample size used by PreProcessing/data_scaling.py. Default uses all generated rows.",
    )
    parser.add_argument(
        "--model",
        choices=["oneclass", "linear", "kernel", "both", "all"],
        default="oneclass",
        help="Model group to train and evaluate. Default keeps the one-command run practical.",
    )
    parser.add_argument(
        "--training-preset",
        choices=["fast", "default"],
        default="fast",
        help="Hyperparameter grid preset for model training.",
    )
    parser.add_argument(
        "--oneclass-training-sample-size",
        type=int,
        default=0,
        help="Rows used for One-Class SVM tuning/final fit. Default 0 uses all train rows.",
    )
    parser.add_argument(
        "--eval-sample-size",
        type=int,
        default=None,
        help="Optional row sample for model evaluation.",
    )
    parser.add_argument(
        "--dry-run-training",
        action="store_true",
        help="Run model training without saving model artifacts.",
    )
    return parser.parse_args()


def python_command(script_path: Path, *args: str) -> list[str]:
    return [str(venv_python_path()), str(script_path), *args]


def path_args(flag: str, value: Path) -> list[str]:
    return [flag, str(value)]


def build_steps(args: argparse.Namespace) -> list[PipelineStep]:
    dataset_dir = ROOT_DIR / "DataSet"
    prep_output_dir = ROOT_DIR / "PreProcessing" / "synthetic_prep_outputs"
    eda_output_dir = ROOT_DIR / "EDA" / "synthetic_eda_outputs"
    model_dir = ROOT_DIR / "Model Training" / "models"
    evaluation_output_dir = ROOT_DIR / "Model Training" / "evaluation_outputs_synthetic"

    merged = dataset_dir / "synthetic_fraud_merged.csv"
    cleaned = dataset_dir / "synthetic_fraud_cleaned.csv"
    transformed = dataset_dir / "synthetic_fraud_transformed.csv"
    reduced = dataset_dir / "synthetic_fraud_transformed_reducted.csv"
    sampled = dataset_dir / "synthetic_fraud_transformed_reducted_sampled.csv"
    train = dataset_dir / "synthetic_fraud_transformed_reducted_scaled_train.csv"
    test = dataset_dir / "synthetic_fraud_transformed_reducted_scaled_test.csv"

    oneclass_model = model_dir / "synthetic_oneclass_rbf_svm_model.pkl"
    linear_model = model_dir / "synthetic_supervised_sgd_svm_model.pkl"
    kernel_model = model_dir / "synthetic_supervised_rbf_svm_model.pkl"

    training_args = [
        "--models",
        args.model,
        "--param-preset",
        args.training_preset,
        "--random-state",
        str(args.random_state),
        *path_args("--input", train),
        *path_args("--model-path", linear_model),
        *path_args("--kernel-model-path", kernel_model),
        *path_args("--oneclass-model-path", oneclass_model),
    ]
    if args.oneclass_training_sample_size > 0:
        training_args.extend(
            ["--oneclass-training-sample-size", str(args.oneclass_training_sample_size)]
        )
    if args.dry_run_training:
        training_args.append("--dry-run")

    evaluation_args = [
        "--models",
        args.model,
        *path_args("--train", train),
        *path_args("--test", test),
        *path_args("--reduced", reduced),
        *path_args("--sampled-source", sampled),
        *path_args("--model", linear_model),
        *path_args("--kernel-model", kernel_model),
        *path_args("--oneclass-model", oneclass_model),
        *path_args("--output-dir", evaluation_output_dir),
        "--random-state",
        str(args.random_state),
    ]
    if args.eval_sample_size is not None:
        evaluation_args.extend(["--eval-sample-size", str(args.eval_sample_size)])

    return [
        PipelineStep(
            "Generate synthetic dataset",
            python_command(
                ROOT_DIR / "DataSet" / "generate_synthetic_fraud_dataset.py",
                *path_args("--output", merged),
                "--rows",
                str(args.rows),
                "--fraud-rate",
                str(args.fraud_rate),
                "--random-state",
                str(args.random_state),
            ),
            (merged,),
        ),
        PipelineStep(
            "Clean missing values",
            python_command(
                ROOT_DIR / "PreProcessing" / "data_cleaning.py",
                *path_args("--input", merged),
                *path_args("--output", cleaned),
                *path_args("--output-dir", prep_output_dir),
            ),
            (cleaned, prep_output_dir / "missing_value_analysis.png"),
        ),
        PipelineStep(
            "Transform features",
            python_command(
                ROOT_DIR / "PreProcessing" / "data_transformation.py",
                *path_args("--input", cleaned),
                *path_args("--output", transformed),
                *path_args("--output-dir", prep_output_dir),
            ),
            (transformed,),
        ),
        PipelineStep(
            "Reduce columns",
            python_command(
                ROOT_DIR / "PreProcessing" / "data_reduction.py",
                *path_args("--input", transformed),
                *path_args("--output", reduced),
                *path_args("--output-dir", prep_output_dir),
            ),
            (reduced,),
        ),
        PipelineStep(
            "Scale and split dataset",
            python_command(
                ROOT_DIR / "PreProcessing" / "data_scaling.py",
                *path_args("--input", reduced),
                *path_args("--sample-output", sampled),
                *path_args("--train-output", train),
                *path_args("--test-output", test),
                *path_args("--output-dir", prep_output_dir),
                "--sample-size",
                str(args.sample_size),
                "--fraud-sample-rate",
                str(args.fraud_rate),
            ),
            (sampled, train, test),
        ),
        PipelineStep(
            "Statistical dataset analysis",
            python_command(ROOT_DIR / "PreProcessing" / "dataset_statistical_analysis.py"),
            (prep_output_dir,),
        ),
        PipelineStep(
            "Exploratory data analysis",
            python_command(
                ROOT_DIR / "EDA" / "eda_analysis.py",
                *path_args("--input", transformed),
                *path_args("--output-dir", eda_output_dir),
            ),
            (eda_output_dir,),
        ),
        PipelineStep(
            "Train model",
            python_command(ROOT_DIR / "Model Training" / "train_unsupervised_svm.py", *training_args),
            () if args.dry_run_training else (model_dir,),
        ),
        PipelineStep(
            "Evaluate model",
            python_command(
                ROOT_DIR / "Model Training" / "evaluate_unsupervised_svm.py",
                *evaluation_args,
            ),
            (evaluation_output_dir,),
        ),
    ]


def print_configuration(args: argparse.Namespace, steps: list[PipelineStep]) -> None:
    table = Table(title="Pipeline Configuration", header_style="bold magenta")
    table.add_column("setting")
    table.add_column("value", justify="right")
    table.add_row("project_root", str(ROOT_DIR))
    table.add_row("python", str(venv_python_path()))
    table.add_row("rows", f"{args.rows:,}")
    table.add_row("fraud_rate", f"{args.fraud_rate:.2%}")
    table.add_row("sample_size", f"{args.sample_size:,}")
    table.add_row("model", args.model)
    table.add_row("training_preset", args.training_preset)
    table.add_row("steps", str(len(steps)))
    console.print(table)


def run_step(index: int, total: int, step: PipelineStep) -> None:
    console.rule(f"[bold cyan]Step {index}/{total}: {step.name}")
    console.print(f"[dim]$ {' '.join(step.command)}[/dim]")

    started_at = time.perf_counter()
    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        TimeElapsedColumn(),
        console=console,
        transient=True,
    ) as progress:
        task_id = progress.add_task(f"Running {step.name}", total=None)
        result = subprocess.run(step.command, cwd=ROOT_DIR, check=False)
        progress.update(task_id, completed=1)

    elapsed = time.perf_counter() - started_at
    if result.returncode != 0:
        raise subprocess.CalledProcessError(result.returncode, step.command)

    console.print(f"[green]Completed:[/green] {step.name} ({elapsed:.1f}s)")
    if step.outputs:
        for output in step.outputs:
            if output.exists():
                console.print(f"  [green]output[/green] {output}")
            else:
                console.print(f"  [yellow]expected output not found[/yellow] {output}")


def run_pipeline(args: argparse.Namespace) -> None:
    steps = build_steps(args)
    console.print(
        Panel.fit(
            "Synthetic fraud anomaly detection pipeline\n"
            "Environment, dataset, preprocessing, EDA, training, and evaluation",
            title="Anomaly Detection Pipeline",
            border_style="cyan",
        )
    )
    print_configuration(args, steps)

    for index, step in enumerate(steps, start=1):
        run_step(index, len(steps), step)

    console.print(
        Panel.fit(
            "Pipeline completed successfully.\n"
            "Generated CSV, PNG, and model/evaluation outputs were overwritten in place.",
            title="Done",
            border_style="green",
        )
    )


def main() -> None:
    args = parse_args()
    if args.skip_setup:
        console.print("[yellow]Setup check skipped by --skip-setup.[/yellow]")

    run_pipeline(args)


if __name__ == "__main__":
    try:
        main()
    except subprocess.CalledProcessError as exc:
        console.print(
            Panel.fit(
                f"Step failed with exit code {exc.returncode}\n"
                f"Command: {' '.join(str(part) for part in exc.cmd)}",
                title="Pipeline Failed",
                border_style="red",
            )
        )
        raise SystemExit(exc.returncode) from exc
